import http from 'node:http'
import { readFileSync, statSync } from 'node:fs'
import { extname, join, normalize } from 'node:path'
import { fileURLToPath } from 'node:url'
const root=join(fileURLToPath(new URL('.',import.meta.url)),'public')
const read=p=>readFileSync(join(root,p),'utf8')
const json=p=>JSON.parse(read(p))
const redirects={'/igor-vepretski':'/about','/press-wall':'/press','/story':'/journal/lifnei-shemehalkim-et-hamaftehot'}
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.xml':'application/xml; charset=utf-8','.txt':'text/plain; charset=utf-8','.svg':'image/svg+xml; charset=utf-8'}
const nav='<header class="topbar"><a class="wordmark" href="/">#7YA</a><nav><a href="/journal">JOURNAL</a><a href="/media">MEDIA</a><a href="/press">PRESS</a><a href="/evidence">EVIDENCE</a><a href="/about">ABOUT</a><a href="/contact">CONTACT</a></nav></header>'
const footer='<footer><span>#7YA</span><span>IGOR VEPRETSKI</span><span>SOURCE-AWARE MEDIA SYSTEM</span></footer>'
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))
const shell=(title,description,path,body,lang='he',dir='rtl',schema='')=>`<!doctype html><html lang="${lang}" dir="${dir}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="https://7ya.io${path}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:image" content="https://7ya.io/og/default.svg"><meta name="twitter:card" content="summary_large_image"><link rel="stylesheet" href="/site.css"><link rel="stylesheet" href="/layout.css"><link rel="stylesheet" href="/components.css"><script src="/site.js" defer></script>${schema}</head><body>${nav}<main class="page">${body}</main>${footer}</body></html>`
const articleSchema='<script type="application/ld+json">{"@context":"https://schema.org","@type":"Article","headline":"לפני שמחלקים את המפתחות","author":{"@type":"Person","name":"Igor Vepretski"},"datePublished":"2026-06-11","mainEntityOfPage":"https://7ya.io/journal/lifnei-shemehalkim-et-hamaftehot"}</script>'
const routes={
'/drops':()=>shell('DROPS | #7YA','#7YA drops archive.','/drops','<p class="kicker">PROGRAM:7YA / SZN:01</p><h1>DROPS</h1><p>Controlled publishing units with source context and canonical routes.</p><section class="grid"><article class="card"><div><p class="provider">DROP:01 / UNIT:TEL-AVIV</p><h3>DISCIPLINE IS FREEDOM.</h3><p>The opening public entry point.</p></div><div class="actions"><a href="/drops/drop-01">OPEN DROP</a></div></article></section>','en','ltr'),
'/drops/drop-01':()=>shell('DROP:01 | #7YA','The opening #7YA system plate.','/drops/drop-01','<p class="kicker">DROP:01 / UNIT:TEL-AVIV / PROGRAM:7YA / SZN:01</p><h1>DISCIPLINE IS FREEDOM.</h1><p>A restrained opening unit. No synthetic hero image. No decorative overload.</p><div class="actions"><a href="/">ENTER</a><a href="/journal">OPEN JOURNAL</a></div>','en','ltr'),
'/about':()=>shell('ABOUT | Igor Vepretski','A documentary introduction to Igor Vepretski.','/about','<p class="kicker">IGOR VEPRETSKI / DOCUMENTARY PAGE</p><h1>ABOUT</h1><section class="grid"><article class="memory"><p class="provider">עלייה</p><p>נולדתי בחרקוב ועליתי לישראל כילד. הסיפור שלי מתחיל בתנועה בין מקומות, שפות וזהויות.</p></article><article class="memory"><p class="provider">בית</p><p>הבית והמשפחה הם לא הערת שוליים. הם חלק מהאחריות שמעצבת את הדרך.</p></article><article class="memory"><p class="provider">שכונה</p><p>ג׳סי כהן היא לא רק נקודה על המפה. היא שכבת זיכרון והקשר לעשייה.</p></article><article class="memory"><p class="provider">שירות</p><p>השירות הציבורי הוא פרק משמעותי בדרך, לא קיצור דרך לסיסמה.</p></article><article class="memory"><p class="provider">אבהות</p><p>אבהות מעמידה את כל השאלות הציבוריות במבחן היומיום.</p></article><article class="memory"><p class="provider">קול</p><p>כתיבה, וידאו ומוזיקה הם אמצעים לביטוי ולשיחה עם הציבור.</p></article><article class="memory"><p class="provider">StartOn</p><p>יוזמה חברתית עצמאית שמוצגת בנפרד מן הזהות האישית.</p></article><article class="memory"><p class="provider">#7YA</p><p>שכבת מדיה, ארכיון ופרסום שמארגנת את הביטוי הציבורי.</p></article></section>'),
'/contact':()=>shell('CONTACT | #7YA','Contact routes for #7YA and Igor Vepretski.','/contact','<p class="kicker">CONTACT</p><h1>CONTACT</h1><p>לשיחה מקצועית, תקשורתית או שיתוף פעולה: השתמשו במפת הקישורים הציבורית.</p><div class="actions"><a href="https://linktr.ee/igor.vepretski" target="_blank" rel="noopener noreferrer">OPEN PUBLIC LINKS</a><a href="https://starton.org.il/" target="_blank" rel="noopener noreferrer">OPEN STARTON</a></div>'),
'/press':()=>shell('PRESS | #7YA','Verified public press and document sources.','/press','<p class="kicker">PRESS / VERIFIED PUBLIC SOURCES</p><h1>PRESS</h1><p>Profile articles, interviews, public documents and selected external profiles. Text-first by design.</p><section class="grid" data-press-grid></section>'),
'/evidence':()=>shell('EVIDENCE WALL | #7YA','Navigable public evidence cards with source and status.','/evidence','<p class="kicker">EVIDENCE WALL</p><h1>EVIDENCE</h1><p>Claims remain connected to source, date, context and review status. Corrections are preserved rather than erased.</p><section class="grid" data-evidence-grid></section>'),
'/journal/lifnei-shemehalkim-et-hamaftehot':()=>shell('לפני שמחלקים את המפתחות: איגור ופרצקי על שייכות, שירות והנהגה','איגור ופרצקי מספר על הדרך מילדות מורכבת בג׳סי כהן לשירות, אבהות ו־StartOn — ועל האחריות לפתוח את הדלת לקולות חדשים שנולדו מתוך החיים עצמם.','/journal/lifnei-shemehalkim-et-hamaftehot','<article class="article-body"><p class="kicker">JOURNAL / PERSONAL ESSAY / 8 MIN READ</p><h1>לפני שמחלקים את המפתחות</h1><p class="note">על הילד שנשא את התווית ״נער בסיכון״, על הדרך שעברתי בתוך מדינת ישראל — ועל האחריות לפתוח את הדלת גם בפני קולות שנולדו מחוץ למסדרונות.</p><p>יש רגעים שבהם אדם מבין שהסיפור האישי שלו איננו רק זיכרון פרטי. הוא הופך לאחריות. לא משום שכל מה שעברתי מעניק לי תשובות, אלא משום שהוא מחייב אותי לשאול מי נשאר מחוץ לחדר כשהחלטות מתקבלות.</p><p>גדלתי בתוך מציאות שלא תמיד התיישבה עם המסלול המסודר שמדמיינים כשמדברים על הצלחה. שכונה, משפחה, מסגרות, שייכות — כל אלה לא היו פרקים נפרדים. הם היו אותו מבחן מתמשך: האם המערכת יודעת לראות ילד לפני שהיא מדביקה לו תווית.</p><blockquote>לפני שמחלקים את המפתחות, צריך לשאול מי מעולם לא הוזמן לעמוד ליד הדלת.</blockquote><p>השירות היה עבורי מסגרת, אחריות ומפגש ישיר עם המדינה. בהמשך, האבהות חידדה את השאלה: איזה מרחב אנחנו משאירים לילדים שלנו, ואיזה מרחב אנחנו בונים לילדים שלא מתחילים מאותה נקודת פתיחה.</p><section class="note"><p class="provider">STARTON / CONTEXT BLOCK</p><p>StartOn מוצגת כאן כיוזמה חברתית עצמאית: ניסיון לבנות מרחב טכנולוגי בטוח, קהילתי ומעשי לבני נוער. תיאור היוזמה אינו מוצג כמדד השפעה מוכח; מקורות ציבוריים והקשרים זמינים בנפרד ב־Evidence Wall.</p></section><p>אני לא מבקש להפוך חיים מורכבים לסיסמה. אני מבקש להשאיר דלת פתוחה גם לקולות שנולדו מחוץ למסדרונות — ולדרוש מכל מערכת ציבורית לבדוק לא רק מי מחזיק במפתח, אלא גם מי עדיין מחכה מעבר לדלת.</p><p class="source-note">EVIDENCE NOTE: autobiographical voice is presented as personal narrative. Public-source claims remain separately attributed in /evidence.</p><div class="actions"><a href="/evidence">OPEN EVIDENCE NOTE</a><a href="/journal">BACK TO JOURNAL</a></div></article>','he','rtl',articleSchema),
'/embed':()=>shell('EMBED | #7YA','Public media embed route with professional fallback.','/embed','<p class="kicker">EMBED ROUTE</p><section data-embed-root></section>')}
const send=(res,status,type,value,headers={})=>{res.writeHead(status,{'content-type':type,...headers});res.end(value)}
const sitemap=()=>`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['/','/drops','/drops/drop-01','/media','/journal','/journal/lifnei-shemehalkim-et-hamaftehot','/press','/evidence','/about','/contact'].map(x=>`<url><loc>https://7ya.io${x}</loc></url>`).join('')}</urlset>`
const rss=()=>`<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>#7YA JOURNAL</title><link>https://7ya.io/journal</link><description>Igor Vepretski / #7YA journal</description><item><title>לפני שמחלקים את המפתחות</title><link>https://7ya.io/journal/lifnei-shemehalkim-et-hamaftehot</link><guid>https://7ya.io/journal/lifnei-shemehalkim-et-hamaftehot</guid><pubDate>Thu, 11 Jun 2026 00:00:00 GMT</pubDate></item></channel></rss>`
const og=(a,b)=>`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630"><rect width="1200" height="630" fill="#0B0B0B"/><text x="84" y="128" fill="#FF5A1F" font-family="monospace" font-size="34">#7YA</text><text x="84" y="328" fill="#F2F2EE" font-family="Arial" font-size="70">${esc(a)}</text><text x="84" y="418" fill="#8A8A8A" font-family="monospace" font-size="24">${esc(b)}</text></svg>`
function staticRoute(path){if(path==='/api/media')return '/api/media.json';if(path==='/api/evidence')return '/api/evidence.json';if(path==='/api/content')return '/api/content.json';if(path==='/'||path.endsWith('/'))return path+'index.html';if(!extname(path))return path+'/index.html';return path}
export function createServer(){return http.createServer((req,res)=>{const path=decodeURI(new URL(req.url,'http://localhost').pathname);if(redirects[path])return send(res,308,'text/plain; charset=utf-8','',{location:redirects[path]});if(path==='/robots.txt')return send(res,200,'text/plain; charset=utf-8','User-agent: *\nAllow: /\nSitemap: https://7ya.io/sitemap.xml\n');if(path==='/sitemap.xml')return send(res,200,'application/xml; charset=utf-8',sitemap());if(path==='/rss.xml')return send(res,200,'application/rss+xml; charset=utf-8',rss());if(path==='/og/default.svg')return send(res,200,'image/svg+xml; charset=utf-8',og('#7YA','DISCIPLINE IS FREEDOM.'));if(path==='/api/press'){const items=json('api/media.json').items.filter(x=>['article','podcast','pdf'].includes(x.type));return send(res,200,'application/json; charset=utf-8',JSON.stringify({capturedDate:'2026-06-11',count:items.length,items}))}if(/^\/embed\/[^/]+\/[^/]+$/.test(path))return send(res,200,'text/html; charset=utf-8',routes['/embed']());if(routes[path])return send(res,200,'text/html; charset=utf-8',routes[path]());let file=normalize(join(root,staticRoute(path)));if(!file.startsWith(root))return send(res,403,'text/plain; charset=utf-8','Forbidden');try{if(!statSync(file).isFile())throw Error('not file');return send(res,200,mime[extname(file)]||'application/octet-stream',readFileSync(file))}catch{return send(res,404,'text/plain; charset=utf-8','Not found')}})}
if(import.meta.url===`file://${process.argv[1]}`)createServer().listen(Number(process.env.PORT||4177),()=>console.log('7ya-site ready'))
