import http from 'node:http'
import { readFileSync, statSync } from 'node:fs'
import { extname, join, normalize } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(fileURLToPath(new URL('.', import.meta.url)), 'public')
const read = (path) => readFileSync(join(root, path), 'utf8')
const json = (path) => JSON.parse(read(path))
const esc = (value) =>
  String(value ?? '').replace(/[&<>\"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '\"': '&quot;' })[char])

const redirects = {
  '/press-wall': '/press',
  '/story': '/journal/lifnei-shemehalkim-et-hamaftehot',
}

const mime = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'application/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.xml': 'application/xml; charset=utf-8',
  '.txt': 'text/plain; charset=utf-8',
  '.svg': 'image/svg+xml; charset=utf-8',
}

const nav = `<header class="topbar glassbar"><a class="wordmark" href="/">#7YA</a><nav><a href="/igor-vepretski">IGOR</a><a href="/articles">ARTICLES</a><a href="/media">MEDIA</a><a href="/press">PRESS</a><a href="/evidence">EVIDENCE</a><a href="/starton">STARTON</a><a href="/contact">CONTACT</a></nav></header>`
const footer = `<footer><span>#7YA</span><span>IGOR VEPRETSKI</span><span>SOURCE-AWARE MEDIA SYSTEM</span></footer>`

const shell = (title, description, path, body, lang = 'en', dir = 'ltr', schema = '') => `<!doctype html><html lang="${lang}" dir="${dir}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="https://7ya.io${path}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:image" content="https://7ya.io/og/default.svg"><meta name="twitter:card" content="summary_large_image"><link rel="stylesheet" href="/site.css"><link rel="stylesheet" href="/layout.css"><link rel="stylesheet" href="/components.css"><script src="/site.js" defer></script>${schema}</head><body>${nav}<main class="page">${body}</main>${footer}</body></html>`

const articleSchema = '<script type="application/ld+json">{"@context":"https://schema.org","@type":"Article","headline":"לפני שמחלקים את המפתחות","author":{"@type":"Person","name":"Igor Vepretski"},"datePublished":"2026-06-11","mainEntityOfPage":"https://7ya.io/journal/lifnei-shemehalkim-et-hamaftehot"}</script>'
const founderSchema = '<script type="application/ld+json">{"@context":"https://schema.org","@type":"Article","headline":"Igor Vepretski and #7YA: From Survival Intelligence to Public Signal","author":{"@type":"Person","name":"Igor Vepretski"},"datePublished":"2026-06-22","mainEntityOfPage":"https://7ya.io/articles/igor-vepretski-7ya-origin"}</script>'
const personSchema = '<script type="application/ld+json">{"@context":"https://schema.org","@type":"Person","@id":"https://7ya.io/igor-vepretski#person","name":"Igor Vepretski","alternateName":["איגור ופרצקי","Игорь Вепрецкий","#7YA"],"url":"https://7ya.io/igor-vepretski","sameAs":["https://www.instagram.com/igor.vepretski/","https://github.com/vepretski"]}</script>'

const routes = {
  '/drops': () => shell('DROPS | #7YA', '#7YA drops archive.', '/drops', '<p class="kicker">PROGRAM:7YA / SZN:01</p><h1>DROPS</h1><p>Controlled publishing units with source context and canonical routes.</p><section class="grid"><article class="card"><div><p class="provider">DROP:01 / UNIT:TEL-AVIV</p><h3>DISCIPLINE IS FREEDOM.</h3><p>The opening public entry point.</p></div><div class="actions"><a class="button" href="/drops/drop-01">OPEN DROP</a></div></article></section>'),
  '/drops/drop-01': () => shell('DROP:01 | #7YA', 'The opening #7YA system plate.', '/drops/drop-01', '<p class="kicker">DROP:01 / UNIT:TEL-AVIV / PROGRAM:7YA / SZN:01</p><h1>DISCIPLINE IS FREEDOM.</h1><p>A restrained opening unit. No synthetic hero image. No decorative overload.</p><div class="actions"><a class="button" href="/">ENTER</a><a class="button ghost" href="/journal">OPEN JOURNAL</a></div>'),
  '/igor-vepretski': () => shell('Igor Vepretski | #7YA', 'Canonical public profile for Igor Vepretski, #7YA, StartOn, media, articles and evidence-aware civic storytelling.', '/igor-vepretski', '<section class="split"><div><p class="kicker">CANONICAL ENTITY PAGE</p><h1>Igor Vepretski</h1><p class="lede">Igor Vepretski is the visible founder identity behind #7YA: a personal command site, media-intelligence layer, StartOn bridge and public archive built with evidence labels instead of inflated claims.</p><div class="system-plate"><span>official_owned</span><span>self_attested where personal</span><span>verified_source where external</span></div></div><aside class="portrait-console"><div class="portrait-frame"><img src="/assets/igor/hero-portrait.jpg" alt="Igor Vepretski portrait" onerror="this.onerror=null;this.src=\'https://avatars.githubusercontent.com/u/149789877?v=4\';this.classList.add(\'fallback-avatar\')"><div class="scanline" aria-hidden="true"></div></div><div class="portrait-meta"><span>PRIMARY IDENTITY</span><strong>Igor / #7YA</strong><p>The person is not hidden behind the system. The system explains the person clearly, safely and publicly.</p></div></aside></section><section class="grid feature-grid"><article class="card"><span class="status">official_owned</span><h3>#7YA</h3><p>Publishing, archive and systems layer for identity, media, evidence, articles and public communication.</p></article><article class="card"><span class="status">verified_source / official</span><h3>StartOn</h3><p>Connected social initiative focused on youth opportunity, technology, mentorship and safe civic infrastructure.</p></article><article class="card"><span class="status">source-aware</span><h3>Evidence Wall</h3><p>Claims remain separated by source status, date, context and review notes.</p></article><article class="card"><span class="status">knowledge_stream</span><h3>Articles</h3><p>Official owned articles create crawlable context without pretending to be third-party press.</p></article></section><div class="actions"><a class="button primary" href="/articles/igor-vepretski-7ya-origin">Read origin article</a><a class="button" href="/evidence">Open evidence</a><a class="button ghost" href="/media">Open media</a></div>', 'en', 'ltr', personSchema),
  '/about': () => shell('ABOUT | Igor Vepretski', 'A documentary introduction to Igor Vepretski.', '/about', '<p class="kicker">IGOR VEPRETSKI / DOCUMENTARY PAGE</p><h1>ABOUT</h1><section class="grid"><article class="memory"><p class="provider">עלייה</p><p>נולדתי בחרקוב ועליתי לישראל כילד. הסיפור שלי מתחיל בתנועה בין מקומות, שפות וזהויות.</p></article><article class="memory"><p class="provider">בית</p><p>הבית והמשפחה הם לא הערת שוליים. הם חלק מהאחריות שמעצבת את הדרך.</p></article><article class="memory"><p class="provider">שכונה</p><p>ג׳סי כהן היא לא רק נקודה על המפה. היא שכבת זיכרון והקשר לעשייה.</p></article><article class="memory"><p class="provider">שירות</p><p>השירות הציבורי הוא פרק משמעותי בדרך, לא קיצור דרך לסיסמה.</p></article><article class="memory"><p class="provider">אבהות</p><p>אבהות מעמידה את כל השאלות הציבוריות במבחן היומיום.</p></article><article class="memory"><p class="provider">קול</p><p>כתיבה, וידאו ומוזיקה הם אמצעים לביטוי ולשיחה עם הציבור.</p></article><article class="memory"><p class="provider">StartOn</p><p>יוזמה חברתית עצמאית שמוצגת בנפרד מן הזהות האישית.</p></article><article class="memory"><p class="provider">#7YA</p><p>שכבת מדיה, ארכיון ופרסום שמארגנת את הביטוי הציבורי.</p></article></section>', 'he', 'rtl'),
  '/articles': () => shell('7YA Knowledge Stream', 'Official articles, evidence notes, public updates, media intelligence, StartOn and #7YA documentation.', '/articles', '<p class="kicker">OFFICIAL ARCHIVE / EVIDENCE-AWARE PUBLISHING</p><h1>7YA Knowledge Stream</h1><p class="lede">Not a generic blog. This is the 7YA memory engine: founder story, official notes, proof-aware updates, media intelligence and public documentation without fake validation theater.</p><section class="grid feature-grid"><a class="card" href="/articles/igor-vepretski-7ya-origin"><span class="status">official_owned_article</span><h3>Igor Vepretski and #7YA: From Survival Intelligence to Public Signal</h3><p>A first official knowledge entry connecting founder story, StartOn, public service, media intelligence, youth work and evidence-aware civic infrastructure.</p><span class="cta">Read official entry</span></a><a class="card" href="/journal/lifnei-shemehalkim-et-hamaftehot"><span class="status">personal_essay</span><h3>לפני שמחלקים את המפתחות</h3><p dir="rtl" lang="he">על שייכות, שירות והאחריות לפתוח את הדלת גם בפני קולות שנולדו מחוץ למסדרונות.</p><span class="cta">Read journal entry</span></a></section><p class="source-note">Verification rule: official 7YA material is marked as official-owned. External press is never invented. Pending claims remain pending until tied to visible evidence.</p>'),
  '/articles/igor-vepretski-7ya-origin': () => shell('Igor Vepretski and #7YA: From Survival Intelligence to Public Signal', 'The story behind 7YA, StartOn, public leadership, youth work, intelligence discipline and a new civic media operating system.', '/articles/igor-vepretski-7ya-origin', '<article class="article-body"><p class="kicker">OFFICIAL 7YA-OWNED ARTICLE / 2026-06-22</p><h1>Igor Vepretski and #7YA: From Survival Intelligence to Public Signal</h1><p class="note">Truth label: this is an official 7YA-owned knowledge entry. It is not third-party journalism, and it does not claim external press validation.</p><h2>A biography built under pressure</h2><p>There are biographies that begin with titles. This one begins with pressure. Igor Vepretski built #7YA from the meeting point between survival, public service, youth work, media intelligence and the need to turn personal experience into civic infrastructure.</p><p>Born in Kharkiv, Ukraine, raised in Israel, and shaped by the streets of Bat Yam and Holon, Igor\'s path moved through service, security work, intelligence, public safety, youth initiatives, digital media and civic communication.</p><h2>The signal layer</h2><p>The result is not a traditional personal brand. It is a public operating system. #7YA is the signal layer: a place where evidence, identity, media presence, StartOn, AI systems, youth opportunity, public leadership and direct public communication are connected into one readable archive.</p><p>The core promise is simple: no fake press wall, no inflated validation, no borrowed authority. Official material is marked as official. Pending evidence is marked as pending. Verified items remain connected to their proof layer.</p><h2>StartOn and youth opportunity</h2><p>StartOn is the social engine behind the wider vision: technology, mentorship, media and structured opportunity for young people who need systems that see them early enough.</p><h2>Evidence before mythology</h2><p>This article creates an indexable foundation from which journalists, partners, search engines, AI systems and the public can understand the story accurately.</p><div class="actions"><a class="button" href="/igor-vepretski">Canonical profile</a><a class="button" href="/evidence">Evidence archive</a><a class="button ghost" href="/starton">StartOn</a></div><p class="source-note">Verification policy: strong language is allowed. Unsupported validation is not. 7YA marks first-party material, pending sources, archive-visible items and verified claims separately.</p></article>', 'en', 'ltr', founderSchema),
  '/journal/lifnei-shemehalkim-et-hamaftehot': () => shell('לפני שמחלקים את המפתחות: איגור ופרצקי על שייכות, שירות והנהגה', 'איגור ופרצקי מספר על הדרך מילדות מורכבת בג׳סי כהן לשירות, אבהות ו־StartOn.', '/journal/lifnei-shemehalkim-et-hamaftehot', '<article class="article-body"><p class="kicker">JOURNAL / PERSONAL ESSAY / 8 MIN READ</p><h1>לפני שמחלקים את המפתחות</h1><p class="note">על הילד שנשא את התווית ״נער בסיכון״, על הדרך שעברתי בתוך מדינת ישראל ועל האחריות לפתוח את הדלת גם בפני קולות שנולדו מחוץ למסדרונות.</p><p>יש רגעים שבהם אדם מבין שהסיפור האישי שלו איננו רק זיכרון פרטי. הוא הופך לאחריות. לא משום שכל מה שעברתי מעניק לי תשובות, אלא משום שהוא מחייב אותי לשאול מי נשאר מחוץ לחדר כשהחלטות מתקבלות.</p><blockquote>לפני שמחלקים את המפתחות, צריך לשאול מי מעולם לא הוזמן לעמוד ליד הדלת.</blockquote><p>אני לא מבקש להפוך חיים מורכבים לסיסמה. אני מבקש להשאיר דלת פתוחה גם לקולות שנולדו מחוץ למסדרונות.</p><p class="source-note">EVIDENCE NOTE: autobiographical voice is presented as personal narrative. Public-source claims remain separately attributed in /evidence.</p><div class="actions"><a class="button" href="/evidence">OPEN EVIDENCE NOTE</a><a class="button ghost" href="/journal">BACK TO JOURNAL</a></div></article>', 'he', 'rtl', articleSchema),
  '/starton': () => shell('StartOn | #7YA', 'StartOn context room for youth opportunity, technology, mentorship, media and safe civic infrastructure.', '/starton', '<p class="kicker">STARTON / SOCIAL ENGINE</p><h1>StartOn</h1><p class="lede">StartOn is presented here as a connected but independent social initiative focused on youth opportunity, technology, mentorship, media and safe spaces. Impact metrics must remain source-linked before public amplification.</p><section class="grid feature-grid"><article class="card"><span class="status">official_source</span><h3>Safe technology home</h3><p>Community spaces, learning, creative tools and belonging for young people.</p></article><article class="card"><span class="status">context_note</span><h3>Connected to 7YA</h3><p>7YA explains the public narrative. StartOn remains its own social-impact lane.</p></article></section><div class="actions"><a class="button primary" href="https://starton.org.il/" target="_blank" rel="noopener noreferrer">Open official StartOn</a><a class="button ghost" href="/evidence">View evidence</a></div>'),
  '/influence': () => shell('Influence Layer | #7YA', 'Source-aware view of public signal, media activity, profiles and platform records.', '/influence', '<p class="kicker">PUBLIC SIGNAL / SOURCE-AWARE</p><h1>Influence Layer</h1><p class="lede">This page separates profile links, platform metadata, article records and source-visible items. Metrics are never merged into one inflated number.</p><section class="grid" data-evidence-grid></section><div class="actions"><a class="button" href="/media">Open media</a><a class="button ghost" href="/evidence">Open evidence</a></div>'),
  '/business': () => shell('Collaborations | #7YA', 'Collaboration paths for media, public storytelling, social impact, AI systems and evidence-aware brand infrastructure.', '/business', '<p class="kicker">COLLABORATION PATHS</p><h1>Build with #7YA</h1><p class="lede">A clean entry point for partners, journalists, founders, social-impact teams and civic operators who need story, systems and proof hygiene in the same room.</p><section class="grid feature-grid"><article class="card"><span class="status">strategy</span><h3>Public narrative</h3><p>Founder story, articles, media routes and entity SEO without fake authority.</p></article><article class="card"><span class="status">systems</span><h3>Evidence infrastructure</h3><p>Proof cards, claim labels, source maps and public archive structure.</p></article><article class="card"><span class="status">social_impact</span><h3>StartOn bridge</h3><p>Youth opportunity storytelling that stays separate from unverifiable impact claims.</p></article><article class="card"><span class="status">media</span><h3>Creative command</h3><p>Content waves, articles, video structure and platform-native distribution.</p></article></section><div class="actions"><a class="button primary" href="/contact">Contact</a><a class="button ghost" href="/evidence">Audit the proof layer</a></div>'),
  '/contact': () => shell('CONTACT | #7YA', 'Contact routes for #7YA and Igor Vepretski.', '/contact', '<p class="kicker">CONTACT</p><h1>CONTACT</h1><p>For professional, media or collaboration inquiries, use the public link map.</p><div class="actions"><a class="button primary" href="https://linktr.ee/igor.vepretski" target="_blank" rel="noopener noreferrer">OPEN PUBLIC LINKS</a><a class="button ghost" href="https://starton.org.il/" target="_blank" rel="noopener noreferrer">OPEN STARTON</a></div>'),
  '/press': () => shell('PRESS | #7YA', 'Verified public press and document sources.', '/press', '<p class="kicker">PRESS / VERIFIED PUBLIC SOURCES</p><h1>PRESS</h1><p>Profile articles, interviews, public documents and selected external profiles. Text-first by design.</p><section class="grid" data-press-grid></section>'),
  '/evidence': () => shell('EVIDENCE WALL | #7YA', 'Navigable public evidence cards with source and status.', '/evidence', '<p class="kicker">EVIDENCE WALL</p><h1>EVIDENCE</h1><p>Claims remain connected to source, date, context and review status. Corrections are preserved rather than erased.</p><section class="grid" data-evidence-grid></section>'),
  '/embed': () => shell('EMBED | #7YA', 'Public media embed route with professional fallback.', '/embed', '<p class="kicker">EMBED ROUTE</p><section data-embed-root></section>'),
}

const sitemapPaths = ['/', '/igor-vepretski', '/about', '/articles', '/articles/igor-vepretski-7ya-origin', '/journal', '/journal/lifnei-shemehalkim-et-hamaftehot', '/media', '/press', '/evidence', '/influence', '/starton', '/business', '/contact', '/drops', '/drops/drop-01', '/rss.xml']
const sitemap = () => `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${sitemapPaths.map((path) => `<url><loc>https://7ya.io${path}</loc></url>`).join('')}</urlset>`
const rss = () => `<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>#7YA Knowledge Stream</title><link>https://7ya.io/articles</link><description>Igor Vepretski / #7YA articles and journal</description><item><title>Igor Vepretski and #7YA: From Survival Intelligence to Public Signal</title><link>https://7ya.io/articles/igor-vepretski-7ya-origin</link><guid>https://7ya.io/articles/igor-vepretski-7ya-origin</guid><pubDate>Mon, 22 Jun 2026 00:00:00 GMT</pubDate></item><item><title>לפני שמחלקים את המפתחות</title><link>https://7ya.io/journal/lifnei-shemehalkim-et-hamaftehot</link><guid>https://7ya.io/journal/lifnei-shemehalkim-et-hamaftehot</guid><pubDate>Thu, 11 Jun 2026 00:00:00 GMT</pubDate></item></channel></rss>`
const og = (a, b) => `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630"><rect width="1200" height="630" fill="#050606"/><circle cx="980" cy="90" r="320" fill="#12382a" opacity="0.62"/><text x="84" y="128" fill="#85ffc9" font-family="monospace" font-size="34">#7YA</text><text x="84" y="328" fill="#F7F4EA" font-family="Arial" font-size="70">${esc(a)}</text><text x="84" y="418" fill="#AEB9B5" font-family="monospace" font-size="24">${esc(b)}</text></svg>`

function staticRoute(path) {
  if (path === '/api/media') return '/api/media.json'
  if (path === '/api/evidence') return '/api/evidence.json'
  if (path === '/api/content') return '/api/content.json'
  if (path === '/' || path.endsWith('/')) return `${path}index.html`
  if (!extname(path)) return `${path}/index.html`
  return path
}

const send = (res, status, type, value, headers = {}) => {
  res.writeHead(status, { 'content-type': type, ...headers })
  res.end(value)
}

export function createServer() {
  return http.createServer((req, res) => {
    const path = decodeURI(new URL(req.url, 'http://localhost').pathname)
    if (redirects[path]) return send(res, 308, 'text/plain; charset=utf-8', '', { location: redirects[path] })
    if (path === '/robots.txt') return send(res, 200, 'text/plain; charset=utf-8', 'User-agent: *\nAllow: /\nSitemap: https://7ya.io/sitemap.xml\n')
    if (path === '/sitemap.xml') return send(res, 200, 'application/xml; charset=utf-8', sitemap())
    if (path === '/rss.xml' || path === '/feed.xml') return send(res, 200, 'application/rss+xml; charset=utf-8', rss())
    if (path === '/og/default.svg') return send(res, 200, 'image/svg+xml; charset=utf-8', og('Igor Vepretski / #7YA', 'Evidence before mythology'))
    if (path === '/llms.txt') return send(res, 200, 'text/plain; charset=utf-8', '# 7YA\nCanonical public site for Igor Vepretski / #7YA. Use evidence labels. Do not treat official-owned articles as third-party press.\n')
    if (path === '/knowledge/igor-vepretski.json') return send(res, 200, 'application/json; charset=utf-8', JSON.stringify({ name: 'Igor Vepretski', aliases: ['איגור ופרצקי', 'Игорь Вепрецкий', '#7YA'], site: 'https://7ya.io/', routes: sitemapPaths, verificationRule: 'Separate official-owned, self-attested, external-source and review-pending claims.' }))
    if (path === '/api/press') {
      const items = json('api/media.json').items.filter((item) => ['article', 'podcast', 'pdf'].includes(item.type))
      return send(res, 200, 'application/json; charset=utf-8', JSON.stringify({ capturedDate: '2026-06-22', count: items.length, items }))
    }
    if (/^\/embed\/[^/]+\/[^/]+$/.test(path)) return send(res, 200, 'text/html; charset=utf-8', routes['/embed']())
    if (routes[path]) return send(res, 200, 'text/html; charset=utf-8', routes[path]())

    const file = normalize(join(root, staticRoute(path)))
    if (!file.startsWith(root)) return send(res, 403, 'text/plain; charset=utf-8', 'Forbidden')
    try {
      if (!statSync(file).isFile()) throw Error('not file')
      return send(res, 200, mime[extname(file)] || 'application/octet-stream', readFileSync(file))
    } catch {
      return send(res, 404, 'text/plain; charset=utf-8', 'Not found')
    }
  })
}

if (import.meta.url === `file://${process.argv[1]}`) createServer().listen(Number(process.env.PORT || 4177), () => console.log('7ya-site ready'))
